package mapper;

import java.util.List;
import model.Players;
import org.apache.ibatis.annotations.Param;

public interface PlayersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    int insert(Players record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    Players selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    List<Players> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    int updateByPrimaryKey(Players record);

    Players selectByPlayerId(Integer playerId);

    int updateByPlayerId(Players record);

    List<Players> selectByModel(Players playerModel);
    List<Players> selectSpeedStaminaShootControl
            (@Param("speed") Integer speed,
             @Param("stamina") Integer stamina,
             @Param("shoot") Integer shoot,
             @Param("control") Integer control);



}