package mapper;

import java.util.List;
import model.Youth;

public interface YouthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youth
     *
     * @mbg.generated Mon Jul 02 19:53:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youth
     *
     * @mbg.generated Mon Jul 02 19:53:17 CST 2018
     */
    int insert(Youth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youth
     *
     * @mbg.generated Mon Jul 02 19:53:17 CST 2018
     */
    Youth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youth
     *
     * @mbg.generated Mon Jul 02 19:53:17 CST 2018
     */
    List<Youth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youth
     *
     * @mbg.generated Mon Jul 02 19:53:17 CST 2018
     */
    int updateByPrimaryKey(Youth record);

    Youth selectByPlayerId(Integer playerId);

    int updateByPlayerId(Youth record);
}