package mapper;

import java.util.List;
import model.Transfers;

public interface TransfersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfers
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfers
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    int insert(Transfers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfers
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    Transfers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfers
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    List<Transfers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfers
     *
     * @mbg.generated Mon Jul 02 19:48:19 CST 2018
     */
    int updateByPrimaryKey(Transfers record);

    Transfers selectByPlayerId(Integer playerId);

    int updateByPlayerId(Transfers record);
}